unit [!UnitName];
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework;

implementation

initialization
  // Register any test cases with the test runner
  [!RegisterCode]
end.

